language: rust
sudo: false
cache: cargo
rust:
  - 1.9.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - ARCH=x86_64
  - FEATURES=""
matrix:
  include:
    - rust: stable
      env:
        - ARCH=i686
    - rust: beta
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - ARCH=x86_64
        - FEATURES="--features simd-accel"
    - rust: nightly
      env:
        - ARCH=x86_64
        - FEATURES="--features avx-accel"
        - RUSTFLAGS="-C target-feature=+avx"
addons:
  apt:
    packages:
      - gcc-multilib
script: |
  echo ARCH=$ARCH
  echo FEATURES=$FEATURES
  echo RUSTFLAGS=$RUSTFLAGS
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  cargo test $FEATURES && cargo bench $FEATURES
